apiVersion: v1
kind: Namespace
metadata:
  name: k8s-papivot-tools
  labels:
    name: k8s-papivot-tools
    app: k8s-papivot-tools
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: installation-scripts
  namespace: k8s-papivot-tools
data:
  wait.sh: |
    #!/bin/bash
    # Modify the wait script to suit your node ready logic
    # E.g. Sleep for 5 mins to allow node to be ready
    sleep 5m

  install.sh: |
    #!/bin/bash

    function getcpid() {
      cpids=`pgrep -P $1|xargs`
      for cpid in $cpids;
      do
        ps --no-header -o pid,ppid,%cpu,time,%mem,rss,vsz,args $cpid
        getcpid $cpid
      done
    }

    if [ ! -f /tmp/install/installation-complete.txt ]
    then
    # --------- Add your node and OS specific commands that need to be executed -----
    # --------- All files are located and executed from /tmp/install folder --------

      while true;
        for i in $(ps -e -o pid,args|grep containerd-shim|grep -v grep|awk '{print $1}')
        do
          getcpid $i
          echo ---
        done
        sleep 2m
      done

    # ----------- Do not modify the lines below ---------------
      touch /tmp/install/installation-complete.txt
    else
      # Script execution was completed previously. Exit gracefully.
      exit 0
    fi
    
  # Add additonal files to be passed thru configmap here
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-configure
  namespace: k8s-papivot-tools
spec:
  selector:
    matchLabels:
      name: node-configure-job
  template:
    metadata:
      labels:
        name: node-configure-job
    spec:
      hostPID: true
      containers:
      - env:
        - name: TINI_SUBREAPER
        image: whoami6443/node-execution:0.0.3
        name: node-configure-pod
        securityContext:
          privileged: true
        volumeMounts:
        - name: install-script
          mountPath: /host-install-files
        - name: host-mount
          mountPath: /host
      volumes:
      - name: install-script
        configMap:
          name: installation-scripts
      - name: host-mount
        hostPath:
          path: /tmp/install
# Use these to control the nodes on which to execute the scripts. 
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
